language:
  - node_js
node_js:
  - 9.7.1
os:
  - linux
before_install:
  - gem update --system
  - gem install sass --version "=3.4.20"
  - gem install compass --version "=1.0.3"
install:
  - npm install
addons:
  ssh_known_hosts:
    - 100.24.187.123
deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r $TRAVIS_BUILD_DIR/dist/ travis@100.24.187.123:/usr/share/nginx/www_joshuapowell_io/httpdocs/www.joshuapowell.io/dist
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_37c35f794c66_key -iv $encrypted_37c35f794c66_iv -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
script:
  - grunt build --environment="production"
