language:
  - node_js
node_js:
  - 9.7.1
os:
  - linux
addons:
  ssh_known_hosts:
    - 75.101.242.153
deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r $TRAVIS_BUILD_DIR/dist/ travis@75.101.242.153:/usr/share/nginx/www_joshuapowell_io/httpdocs/www.joshuapowell.io/dist
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_37c35f794c66_key -iv $encrypted_37c35f794c66_iv -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
