language:
  - python
python:
  - 2.7
os:
  - linux
install:
  - pip install -r requirements.txt
addons:
  ssh_known_hosts:
    - $TRAVIS_DEPLOY_IP
deploy:
  provider: script
  skip_cleanup: true
  script:
    - rsync -r $TRAVIS_BUILD_DIR/dist/ $TRAVIS_DEPLOY_DIR/dist
  on:
    branch: master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_37c35f794c66_key -iv $encrypted_37c35f794c66_iv -in travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ~/.ssh/travis_rsa
  - ssh-add ~/.ssh/travis_rsa
script:
  - python runserver.py --environment="build"
